# Generated by Django 4.1.5 on 2023-01-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('text', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Key_Skills_Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField()),
                ('key_skill_1', models.CharField(max_length=50)),
                ('key_skill_2', models.CharField(max_length=50)),
                ('key_skill_3', models.CharField(max_length=50)),
                ('key_skill_4', models.CharField(max_length=50)),
                ('key_skill_5', models.CharField(max_length=50)),
                ('key_skill_6', models.CharField(max_length=50)),
                ('key_skill_7', models.CharField(max_length=50)),
                ('key_skill_8', models.CharField(max_length=50)),
                ('key_skill_9', models.CharField(max_length=50)),
                ('key_skill_10', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('USD', models.FloatField(default=60.66)),
                ('RUR', models.FloatField(default=1)),
                ('EUR', models.FloatField(default=59.9)),
                ('KZT', models.FloatField(default=0.13)),
                ('UAH', models.FloatField(default=1.64)),
                ('BYR', models.FloatField(default=23.91)),
            ],
        ),
        migrations.CreateModel(
            name='Recent_Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('key_skills', models.TextField(null=True)),
                ('salary_from', models.CharField(max_length=20)),
                ('salary_to', models.CharField(max_length=20)),
                ('area_name', models.CharField(max_length=50)),
                ('published_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Salary_Count_By_City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('selected_vacancies_statistics', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Salary_Info_By_Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField()),
                ('all_vac_level_statistics', models.IntegerField()),
                ('slctd_vac_level_statistics', models.IntegerField()),
                ('all_vac_count_statistics', models.IntegerField()),
                ('slctd_vac_count_statistics', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Salary_Level_By_City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('all_vacancies_statistics', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('key_skills', models.TextField(null=True)),
                ('salary_from', models.CharField(max_length=20)),
                ('salary_to', models.CharField(max_length=20)),
                ('area_name', models.CharField(max_length=50)),
                ('published_at', models.DateTimeField()),
            ],
        ),
    ]
