# Generated by Django 4.1.5 on 2023-01-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.SmallIntegerField()),
                ('USD', models.FloatField(default=60.66)),
                ('RUR', models.FloatField(default=1)),
                ('EUR', models.FloatField(default=59.9)),
                ('KZT', models.FloatField(default=0.13)),
                ('UAH', models.FloatField(default=1.64)),
                ('BYR', models.FloatField(default=23.91)),
            ],
        ),
        migrations.CreateModel(
            name='Recent_Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('key_skills', models.TextField(null=True)),
                ('salary_from', models.CharField(max_length=20)),
                ('salary_to', models.CharField(max_length=20)),
                ('area_name', models.CharField(max_length=80)),
                ('published_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('key_skills', models.TextField(null=True)),
                ('salary_from', models.CharField(max_length=20)),
                ('salary_to', models.CharField(max_length=20)),
                ('area_name', models.CharField(max_length=80)),
                ('published_at', models.DateTimeField()),
            ],
        ),
    ]
