# Generated by Django 4.1.5 on 2023-01-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryInfoByCityGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph_title', models.CharField(max_length=50, verbose_name='Название графика')),
                ('graph', models.ImageField(upload_to='graphs/%Y/%m/%d/', verbose_name='Файл графика')),
            ],
            options={
                'verbose_name': 'График статистики по городам',
                'verbose_name_plural': 'Графики статистики по городам',
            },
        ),
        migrations.CreateModel(
            name='SalaryInfoByYearGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph_title', models.CharField(max_length=50, verbose_name='Название графика')),
                ('graph', models.ImageField(upload_to='graphs/%Y/%m/%d/', verbose_name='Файл графика')),
            ],
            options={
                'verbose_name': 'График статистики по годам',
                'verbose_name_plural': 'Графики статистики по годам',
            },
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
        migrations.DeleteModel(
            name='Vacancy',
        ),
        migrations.AlterModelOptions(
            name='recentvacancy',
            options={'verbose_name': 'Недавняя вакансия', 'verbose_name_plural': 'Недавние вакансии'},
        ),
        migrations.AlterModelOptions(
            name='salarycountbycity',
            options={'verbose_name': 'Число вакансий по городам', 'verbose_name_plural': 'Число вакансий по городам'},
        ),
        migrations.AlterModelOptions(
            name='salarylevelbycity',
            options={'verbose_name': 'Уровень зарплат вакансий по городам', 'verbose_name_plural': 'Уровни зарплат вакансий по городам'},
        ),
        migrations.AlterField(
            model_name='aboutprofession',
            name='text',
            field=models.TextField(null=True, verbose_name='Текст описания'),
        ),
        migrations.AlterField(
            model_name='aboutprofession',
            name='title',
            field=models.TextField(null=True, verbose_name='Заголовок к тексту'),
        ),
    ]
