# Generated by Django 4.1.5 on 2023-01-14 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_salaryinfobycitygraph_salaryinfobyyeargraph_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutProfession',
        ),
    ]
